\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\PassOptionsToPackage{usenames,dvipsnames}{color} % color is loaded by hyperref
\hypersetup{unicode=true,
            pdftitle={Complex and Social Networks: Lab session 7},
            pdfauthor={Wilmer Uruchi \& Egon Ferri},
            colorlinks=true,
            linkcolor=Maroon,
            citecolor=Blue,
            urlcolor=blue,
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Complex and Social Networks: Lab session 7}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \subtitle{Simulation of SIS model over networks}
  \author{Wilmer Uruchi \& Egon Ferri}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

In this session we will simulate the spreading of a disease in the SIS
model and check that the epidemic threshold for arbitrary networks is
indeed \(\frac{1}{\lambda}\) as forecasted by {[}Chakrabarti et al.,
2008{]}. In particular, we consider the spreading of the disease
following these rules at each time step:

\begin{itemize}
\tightlist
\item
  An infected node recovers with probability \(\gamma\)
\item
  An infected node attemps to infect each neighbor with probability
  \(\beta\)
\end{itemize}

Initially, only a random fraction \(p_0\) of nodes are infected.

\section{Methods}\label{methods}

\subsection{Models}\label{models}

\subsubsection{Base}\label{base}

The model that we use to simulate is the following:

\begin{itemize}
\tightlist
\item
  Let \(x_i(t)\) be the probability that node i is infected at time t
\item
  Let \(\zeta_i(t)\) be the probability that a node i will not receive
  infections from its neighbors in the next time step.
\end{itemize}

\[
\begin{aligned} \zeta_{i}(t) &=\prod_{j: i-j} \overbrace{x_{j}(t-1)(1-\beta)}^{j \text { fails to pass infection }}+\overbrace{\left(1-x_{j}(t-1)\right)}^{j \text { is not infected }} \\ &=\prod_{j: i-j} 1-x_{j}(t-1) \beta \end{aligned}
\]

\[
x_{i}(t)=1-\left(1-(1-\gamma) x_{i}(t-1)\right) \zeta_{i}(t)
\] Finally, the fraction of infecteds is computed as:

\[
x(t)=\sum_{i} x_{i}(t)
\]

\subsubsection{Simplified}\label{simplified}

In some cases, we can use a simplified version of the model, since if
the graph is \href{https://en.wikipedia.org/wiki/Regular_graph}{regular}
is easy to see that \(x_i\) is the same \(\forall i\), and the same is
true for \(\zeta_i\).

So we can speed up the calculation without loosing information.

For example, using a regular undirected lattice with \(1000\) nodes and
\(1\) neigbor, we can take a glance to result obtained with the same set
of parameters, both with the base and the simplified model.

\includegraphics{task_7_files/figure-latex/unnamed-chunk-4-1.pdf}

\subsection{Ensamble of graphs}\label{ensamble-of-graphs}

All the networks have \(1000\) nodes, and are connected.

We calculate here the max eigenvalue and the threshold
(\(\frac{1}{\lambda_1}\)) that we'll need in the tasks.

\begin{table}[H]

\caption{\label{tab:unnamed-chunk-8}Data}
\centering
\begin{tabular}[t]{lrrrr}
\toprule
  & Number of edges & Leading eigenvalue & Trashold & Mean degree\\
\midrule
Lattice with 1 neighbor & 1000 & 2.00000 & 0.5000000 & 2.000\\
Lattice with 2 neighbor & 2000 & 4.00000 & 0.2500000 & 4.000\\
Erdos renyi with p=0.015 & 7508 & 16.10662 & 0.0620863 & 15.016\\
Erdos renyi with p=0.1 & 49826 & 100.53127 & 0.0099472 & 99.652\\
Barabasi albert & 50500 & 190.69987 & 0.0052438 & 101.000\\
Complete graph & 499500 & 999.00000 & 0.0010010 & 999.000\\
\bottomrule
\end{tabular}
\end{table}

Note: everything in the construction of the graphs is standard. For
Barabasi-Albert we used as a starting point a lattice of \(100\) nodes,
and we added 56 edges each time to have a number of edges similar to the
second Erdos-Renyi graph, for comparison. We also specified a
\(\gamma = 2\) for the preferential attachment model to get a strong
effect that could help us emphasize results.

\section{Results}\label{results}

\subsection{Task 1: what network is more prone to
epidemic?}\label{task-1-what-network-is-more-prone-to-epidemic}

We decided to leave \(p_0\) fixed, and inspect the behaviour at first by
changing \(\beta\) with \(\gamma\) fixed, and then doing the opposite in
the next step.

\subsubsection{Modeling with different
betas}\label{modeling-with-different-betas}

\includegraphics{task_7_files/figure-latex/unnamed-chunk-10-1.pdf}

As we expect, more dense networks are more epidemic-prone.

An interesting thing to notice is that the degree distribution does not
seems to affect the behaviour of the spread, since, an Erdos-Renyi graph
and an Barabasi-Albert graph (with strong preferential attachment) seems
to have almost the same resistence to the virus, ceteris paribus.

\subsubsection{Modeling with different
gammas}\label{modeling-with-different-gammas}

For this experiment we are leaving \(p_0\) fixed as in the previous
experiment. In a first attempt we use \(\beta = 0.5\) and try with
different \(\gamma\), then we try again with \(\beta = 0.5\) and the
\(\gamma\) values as before.

\subsection{\texorpdfstring{For
\(\beta = 0.5\)}{For \textbackslash{}beta = 0.5}}\label{for-beta-0.5}

We are trying \(\beta = 0.5\) because it gave the best result in the
previous experiment.

\includegraphics{task_7_files/figure-latex/unnamed-chunk-12-1.pdf}

\subsection{\texorpdfstring{For
\(\beta = 0.25\)}{For \textbackslash{}beta = 0.25}}\label{for-beta-0.25}

Since \(\beta = 0.5\) did not produce much variation for different
\(\gamma\), we are now trying the second best result \(\beta = 0.1\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-14-1.pdf}

\subsection{Task 2: are simulation results consistent with theory
thresholds?}\label{task-2-are-simulation-results-consistent-with-theory-thresholds}

We have that if \(\frac{\beta}{\gamma} > \frac{1}{\lambda_1}\) then the
epidemic occurs.

For our subjects we have that:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Lattice with 1 neighbor using \$\lambda\_1 = 2
  \implies \frac{\beta}{\gamma} \textgreater{} threshold = 0.5 \$
\item
  Lattice with 2 neighbor using \$\lambda\_1 = 4
  \implies \frac{\beta}{\gamma} \textgreater{} threshold = 0.25 \$
\item
  Erdos-Renyi with p=0.015 using \$\lambda\_1 = 15.94737
  \implies \frac{\beta}{\gamma} \textgreater{} threshold = 0.0627063 \$
\item
  Erdos-Renyi with p=0.1 using \$\lambda\_1 = 101.55027
  \implies \frac{\beta}{\gamma} \textgreater{} threshold = 0.0098473 \$
\item
  Barabasi-Albert model using \$\lambda\_1 = 191.24417
  \implies \frac{\beta}{\gamma} \textgreater{} threshold = 0.0052289 \$
\item
  Complete Graph model using \$\lambda\_1 = 999
  \implies \frac{\beta}{\gamma} \textgreater{} threshold = 0.0010010 \$
\end{enumerate}

We have already seen that \(\beta = 0.5\) guarantees the threshold in
all instances considered for experimentation; however, this might imply
\(\gamma = 1\) for some instances, which in turn implies a too high
probability of recovering. So, we will change the value of \(\beta\) for
each subject so we do not come into situations where \(\gamma \geq 1\),
then we pick two values for \(\gamma\) one that takes
\(\frac{\beta}{\gamma}\) slightly above the threshold and one slightly
below.

\section{Lattice with 1 neighbor}\label{lattice-with-1-neighbor}

For \(\frac{1}{\lambda_1} = 0.5\) `Lattice with 1 neig above threshold'
using \(\beta = 0.25\) \(\gamma =0.3\) that results in
\(\frac{\beta}{\gamma} = 0.8333\) `Lattice with 1 neig below threshold'
using \(\beta = 0.25\) \(\gamma =0.7\) that results in
\(\frac{\beta}{\gamma} = 0.3571\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-16-1.pdf}

\section{Lattice with 2 neighbor}\label{lattice-with-2-neighbor}

For \(\frac{1}{\lambda_1} = 0.25\) `Lattice with 2 neig above threshold'
has \(\beta = 0.25\) \(\gamma =0.8\) which results in
\(\frac{\beta}{\gamma} = 0.3125\) `Lattice with 2 neig below threshold'
has \(\beta = 0.15\) \(\gamma =0.9\) which results in
\(\frac{\beta}{\gamma} = 0.1667\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-17-1.pdf}

\section{Erdos-Renyi with p=0.015}\label{erdos-renyi-with-p0.015}

For \(\frac{1}{\lambda_1} = 0.0627063\) `Erdos-Renyi with p=0.015' has
\(\beta = 0.01\) \(\gamma =0.1\) which results in
\(\frac{\beta}{\gamma} = 0.1\) `Erdos-Renyi with p=0.015' has
\(\beta = 0.01\) \(\gamma =0.2\) which results in
\(\frac{\beta}{\gamma} = 0.05\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-18-1.pdf}

\section{Erdos-Renyi with p=0.1}\label{erdos-renyi-with-p0.1}

For \(\frac{1}{\lambda_1} = 0.0098473\) `Erdos-Renyi with p=0.1' has
\(\beta = 0.001\) \(\gamma =0.07\) which results in
\(\frac{\beta}{\gamma} = 0.01428\) `Erdos-Renyi with p=0.1' has
\(\beta = 0.001\) \(\gamma =0.15\) which results in
\(\frac{\beta}{\gamma} = 0.00667\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-19-1.pdf}

\section{Barabasi-Albert}\label{barabasi-albert}

For \(\frac{1}{\lambda_1} = 0.0052289\) `Erdos-Renyi with p=0.1' has
\(\beta = 0.001\) \(\gamma =0.15\) which results in
\(\frac{\beta}{\gamma} = 0.00667\) `Erdos-Renyi with p=0.1' has
\(\beta = 0.001\) \(\gamma =0.22\) which results in
\(\frac{\beta}{\gamma} = 0.00454\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-20-1.pdf}

\section{Complete Graph}\label{complete-graph}

For \(\frac{1}{\lambda_1} = 0.001001\) `Complete Graph' using
\(\beta = 0.0009\) \(\gamma =0.8\) which results in
\(\frac{\beta}{\gamma} = 0.001125\) `Complete Graph' using
\(\beta = 0.0009\) \(\gamma =0.95\) which results in
\(\frac{\beta}{\gamma} = 0.000947\)

\includegraphics{task_7_files/figure-latex/unnamed-chunk-21-1.pdf}

\section{Discussion}\label{discussion}

For changing \(\gamma\), we can see that it has a noticeable effect in
graph that are not dense. The more dense the graph is, the higher the
probability that a node is infected by any of its neighbors, so the
probability of recovering does not have a stronger impact as it has in
sparse graphs. It seems as an intuitive result but it is interesting to
see it as a comparison in graphs whose structures we have already
analyzed in previous works.

While experiment with the threshold \(\frac{1}{\lambda_1}\) we can see
that the closer we get to the threshold, from above or below, the harder
it is to determine a difference visually. In some cases we see that the
chart shows a downwards tendency, as if the threshold were not tight
enough, and that might a plausible point; however, lets remember that
the definition of epidemic does not state that the `sicknes' should
spread to the whole population but to a significant portion. In our
experimentation we see that for those tests `slightly' above the
threshold, this definition holds and the agent (or sickness) has spread
to significant fraction of the population after the given iterations,
then, the more the positive difference between the threshold and the
value used, the higher the fraction of the population infected.

comment results


\end{document}
